### PR TITLE
Updated Identifier

### PR DESCRIPTION
**Pull request by Mofetoluwa**

### CODE REVIEW

**Comment by Mofetoluwa** [comment]
Alright let me update that...

**Comment by artitw** [comment]
Please also include the score in the tuple as well if possible. Thanks so much

**Comment by artitw** [comment]
Not F1 score, I was referring to the classification score if the model output provides it. No worries if we don't have it

**Comment by Mofetoluwa** [comment]
Hi Art @artitw 

It's been a while :), I hope you're doing great...

I wasn't able to get the classification score, but I have updated the predictions and the diagram in the README.

**Comment by artitw** [comment]
@Mofetoluwa thanks for the update on this. Excited to have your contribution here.

**Comment by Mofetoluwa** [comment]
Glad to contribute 😊

**Pull request merged**
